### ISSUE TITLE
[BUG] Altitude bug does not go to altitude selected on autopilot panel

### ISSUE THREAD

**Issue by larrydingus** [wpine215/msfs-a320neo#343]
The altitude bug on the PFD does not go to the corresponding altitude that is indicated on the autopilot panel. It seems to not want to go outside of the altitude tape on the PFD. 

**To Reproduce**
1. Rotate altitude knob on autopilot panel
2. Look at PFD and the altitdue bug does not leave the PFD

**Expected behavior**
Altitude bug on PFD should go to the altitude that is on the autopilot panel

![Screenshot (3)](https://user-images.githubusercontent.com/70465643/92061251-c9b74d80-ed63-11ea-85cf-86cbd7353431.png)
![Screenshot (4)](https://user-images.githubusercontent.com/70465643/92061256-cd4ad480-ed63-11ea-9f18-39a9c307b44a.png)

As you can see the altitude bug stays in the same position and basically follows the indicated altitude rather than going to the altitude I have chosen on the autopilot panel until I get to the altitude I want, which then it reads correctly.

**Comment by A320pilotIRL** [comment]
This is a big issue. Should NEVER need to push/pull the ALT knob in order to change the altitude on the PFD

**Comment by nabil74** [comment]
I thought this issue was already resolved.
on my dev 0.1.1 installation when i adjsut the altitude value on the autopilot, the altitude changes on the pfd to match.

**Comment by larrydingus** [comment]
> I thought this issue was already resolved.
> on my dev 0.1.1 installation when i adjsut the altitude value on the autopilot, the altitude changes on the pfd to match.

I just installed the latest dev installation and the blue altitude bug is working better but it still does not completely disappear. It is indicating the correct altitude above and below the altimeter tape (i.e. says 35,000 when set to 35,000) but the actual altitude bug on the altimeter tape is not disappearing like it should if the desired altitude is not within 1,000 feet. Try reinstalling the latest dev release and see if it is still working properly for you. If it is, then it might just be me.

**Comment by AdenFlorian** [comment]
I broke this, I will fix this....

**Comment by Coralec** [comment]
Tested on latest dev branch. It appears to be working properly.
